/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/map'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedChargerIdRouteImport } from './routes/_authenticated/charger.$id'
import { Route as AuthenticatedMerchantIndexRouteImport } from './routes/_authenticated/merchant.index'
import { Route as AuthenticatedMerchantChargersRouteImport } from './routes/_authenticated/merchant.chargers'
import { Route as AuthenticatedMerchantReportsRouteImport } from './routes/_authenticated/merchant.reports'
import { Route as AuthenticatedSessionIdRouteImport } from './routes/_authenticated/session.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChargerIdRoute = AuthenticatedChargerIdRouteImport.update({
  id: '/charger/$id',
  path: '/charger/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMerchantIndexRoute =
  AuthenticatedMerchantIndexRouteImport.update({
    id: '/merchant/',
    path: '/merchant/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMerchantChargersRoute =
  AuthenticatedMerchantChargersRouteImport.update({
    id: '/merchant/chargers',
    path: '/merchant/chargers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMerchantReportsRoute =
  AuthenticatedMerchantReportsRouteImport.update({
    id: '/merchant/reports',
    path: '/merchant/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSessionIdRoute = AuthenticatedSessionIdRouteImport.update({
  id: '/session/$id',
  path: '/session/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/map': typeof AuthenticatedMapRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/charger/$id': typeof AuthenticatedChargerIdRoute
  '/merchant/chargers': typeof AuthenticatedMerchantChargersRoute
  '/merchant/reports': typeof AuthenticatedMerchantReportsRoute
  '/session/$id': typeof AuthenticatedSessionIdRoute
  '/merchant/': typeof AuthenticatedMerchantIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/map': typeof AuthenticatedMapRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/charger/$id': typeof AuthenticatedChargerIdRoute
  '/merchant/chargers': typeof AuthenticatedMerchantChargersRoute
  '/merchant/reports': typeof AuthenticatedMerchantReportsRoute
  '/session/$id': typeof AuthenticatedSessionIdRoute
  '/merchant': typeof AuthenticatedMerchantIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/charger/$id': typeof AuthenticatedChargerIdRoute
  '/_authenticated/merchant/chargers': typeof AuthenticatedMerchantChargersRoute
  '/_authenticated/merchant/reports': typeof AuthenticatedMerchantReportsRoute
  '/_authenticated/session/$id': typeof AuthenticatedSessionIdRoute
  '/_authenticated/merchant/': typeof AuthenticatedMerchantIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/history'
    | '/map'
    | '/profile'
    | '/charger/$id'
    | '/merchant/chargers'
    | '/merchant/reports'
    | '/session/$id'
    | '/merchant/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/history'
    | '/map'
    | '/profile'
    | '/charger/$id'
    | '/merchant/chargers'
    | '/merchant/reports'
    | '/session/$id'
    | '/merchant'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/history'
    | '/_authenticated/map'
    | '/_authenticated/profile'
    | '/_authenticated/charger/$id'
    | '/_authenticated/merchant/chargers'
    | '/_authenticated/merchant/reports'
    | '/_authenticated/session/$id'
    | '/_authenticated/merchant/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/charger/$id': {
      id: '/_authenticated/charger/$id'
      path: '/charger/$id'
      fullPath: '/charger/$id'
      preLoaderRoute: typeof AuthenticatedChargerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/merchant/': {
      id: '/_authenticated/merchant/'
      path: '/merchant'
      fullPath: '/merchant/'
      preLoaderRoute: typeof AuthenticatedMerchantIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/merchant/chargers': {
      id: '/_authenticated/merchant/chargers'
      path: '/merchant/chargers'
      fullPath: '/merchant/chargers'
      preLoaderRoute: typeof AuthenticatedMerchantChargersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/merchant/reports': {
      id: '/_authenticated/merchant/reports'
      path: '/merchant/reports'
      fullPath: '/merchant/reports'
      preLoaderRoute: typeof AuthenticatedMerchantReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/session/$id': {
      id: '/_authenticated/session/$id'
      path: '/session/$id'
      fullPath: '/session/$id'
      preLoaderRoute: typeof AuthenticatedSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedChargerIdRoute: typeof AuthenticatedChargerIdRoute
  AuthenticatedMerchantChargersRoute: typeof AuthenticatedMerchantChargersRoute
  AuthenticatedMerchantReportsRoute: typeof AuthenticatedMerchantReportsRoute
  AuthenticatedSessionIdRoute: typeof AuthenticatedSessionIdRoute
  AuthenticatedMerchantIndexRoute: typeof AuthenticatedMerchantIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedChargerIdRoute: AuthenticatedChargerIdRoute,
  AuthenticatedMerchantChargersRoute: AuthenticatedMerchantChargersRoute,
  AuthenticatedMerchantReportsRoute: AuthenticatedMerchantReportsRoute,
  AuthenticatedSessionIdRoute: AuthenticatedSessionIdRoute,
  AuthenticatedMerchantIndexRoute: AuthenticatedMerchantIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
